### ISSUE TITLE
synosaurus-lookup only uses WordNet

### ISSUE THREAD

**Issue by timmli** [hpdeifel/synosaurus#4] opened 2017-06-15 19:58 UTC
I told synosaurus to use OpenThesaurus with `(setq synosaurus-backend 'synosaurus-backend-openthesaurus)`. However, when using `synsaurus-lookup`, the following error message is shown: 
> Searching for program: No such file or directory, wn

Obviously, it still tries to use WordNet, which is not installed on my machine. 

No problems with `synosaurus-choose-and-replace`.

**Comment by theldoria** [comment] 2017-06-17 07:53
I was surprised by this dependency. It's not mentiond in the readme, but one should know that.

**Comment by hpdeifel** [comment] 2017-06-21 08:26
I can reproduce that. The problem seems to be that the global binding of the variable `synosaurus-backend` is used for backend selection instead of the local one. I will look into that.

In the meantime, you can set the backend globally (as opposed to buffer-local) with:

    (setq-default synosaurus-backend 'synosaurus-backend-openthesaurus)

**Comment by hpdeifel** [comment] 2017-06-21 16:47
Should be fixed now, but #5 still remains

**Closed** 2017-06-21 16:47 UTC
Labels: bug

**Comment by hpdeifel** [comment] 2017-06-21 17:00
And #5 is fixed. Everything should work now

**Comment by timmli** [comment] 2017-06-23 06:58
It works for me. Thanks!
